version: "3"
services:
  app:
    image: flask-starter
    ports:
      - 8000:5000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:12.11
    restart: always
    
    environment:
      - POSTGRES_USER=starterkit
      - POSTGRES_PASSWORD=starterkit
      - POSTGRES_DB=starterkitdb
      - PORT=5432
